# Generated by Django 4.0.4 on 2022-05-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(max_length=200)),
                ('timestamp', models.FloatField()),
                ('elaboration', models.TextField()),
                ('emotion', models.CharField(max_length=200)),
                ('meeeting_hours', models.FloatField()),
                ('platform', models.CharField(max_length=200)),
                ('private_elaboration', models.TextField()),
                ('reactions', models.CharField(max_length=200)),
                ('selection', models.CharField(max_length=200)),
                ('slack_message_id', models.CharField(max_length=200)),
                ('slack_org_id', models.CharField(max_length=200)),
                ('slack_team_id', models.CharField(max_length=200)),
                ('slack_user_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('green_percentage', models.FloatField()),
                ('common_emotion', models.CharField(max_length=200)),
                ('team_id', models.CharField(max_length=200)),
            ],
        ),
    ]
