# Generated by Django 4.0.4 on 2022-05-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ryg_dashboard', '0002_emot_by_date_green_by_date_green_by_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Num_check_ins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_ins', models.IntegerField()),
            ],
        ),
    ]
